#!/usr/bin/python
import subprocess
import os
import sys

salt = sys.argv[3]
hash01 = sys.argv[2]

arquivo = sys.argv[1]

with open(arquivo, "r", encoding="iso-8859-1") as file:
    for senha in file:
        comando = ["openssl", "passwd", "-6", "-salt", salt, senha.strip()]  # Remova os caracteres de nova linha
        resultado = subprocess.run(comando, capture_output=True, text=True)
        saida = resultado.stdout.strip()  # Remova os caracteres de nova linha
     
        if saida == hash01:
            print(senha.strip())

print("===== Finalizado =====")
